/*
*  uChip Game Map Editor. A simple editor and integrated utility for tile-based games.
*
*  Copyright 2019-2020 Nicola Wrachien (next-hack.com)
*
*  This file is part of uChip Simple VGA Console Kernel Library.
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program  is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*  tl;dr
*  Do whatever you want, this program is free! Though we won't
*  reject donations https://next-hack.com/index.php/donate/ :)
*
*/
package uchipgamemapeditor;

public class ExportTileAsCfileDialog extends javax.swing.JDialog
{
    static final int BIGENDIAN = 0;
    static final int LITTLEENDIAN = 1;
    static final int PICTUREARRAYMODE = 0;   // not yet implemented
    static final int TILEARRAYMODE = 1;
    static final int FASTDMAMODE = 2;
    static final int TILEARRAYMODEUCHIPVGA8BIT = 3;
    static final int TILEARRAYMODEUCHIPVGA4BIT = 4;
     static final int TILEARRAYMODEUCHIPVGA2BIT = 5;
    boolean confirmed = false;
    /**
     * Creates new form ExportTileAsCfileDialog
     */
    int getExportMode()
    {
        if (jRadioButtonFastDMA.isSelected())
            return FASTDMAMODE;
        else if (jRadioButtonTile.isSelected())
            return TILEARRAYMODE;
        else if (jRadioButton8bpp.isSelected())
            return TILEARRAYMODEUCHIPVGA8BIT;
        else if (jRadioButton4bpp.isSelected())
            return TILEARRAYMODEUCHIPVGA4BIT;
        else 
            return TILEARRAYMODEUCHIPVGA2BIT;
    }
    int getEndianess()
    {
        if (jRadioButtonBigEndian.isSelected())
            return BIGENDIAN;
        else 
            return LITTLEENDIAN;       
    }
    public ExportTileAsCfileDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonTile = new javax.swing.JRadioButton();
        jRadioButtonFastDMA = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonBigEndian = new javax.swing.JRadioButton();
        jRadioButtonLittleEndian = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton8bpp = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton4bpp = new javax.swing.JRadioButton();
        jRadioButton2bpp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select how to export the tile set");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTile);
        jRadioButtonTile.setText("Array of n x-by-y RGB 565 pixel tiles (for background slices)");

        buttonGroup1.add(jRadioButtonFastDMA);
        jRadioButtonFastDMA.setText("Array of n tiles, 2-column wise, RGB565 (for fast 32-bit DMA).");

        jLabel2.setText("Endianess only for RGB 565 modes:");

        buttonGroup2.add(jRadioButtonBigEndian);
        jRadioButtonBigEndian.setSelected(true);
        jRadioButtonBigEndian.setText("Big Endian (Display)");

        buttonGroup2.add(jRadioButtonLittleEndian);
        jRadioButtonLittleEndian.setText("Little Endian");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton8bpp);
        jRadioButton8bpp.setText("Array of n x-by-y 8bpp pixel tiles (for uChip Simple VGA Console)");

        jLabel3.setText("Array format:");

        buttonGroup1.add(jRadioButton4bpp);
        jRadioButton4bpp.setSelected(true);
        jRadioButton4bpp.setText("Array of n x/2-by-y 4bpp pixel tiles (for uChip Simple VGA Console)");

        buttonGroup1.add(jRadioButton2bpp);
        jRadioButton2bpp.setText("Array of n x/4-by-y 2bpp pixel tiles (for uChip Simple VGA Console)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton8bpp)
                            .addComponent(jRadioButtonTile)
                            .addComponent(jRadioButtonFastDMA)
                            .addComponent(jRadioButton4bpp)
                            .addComponent(jRadioButton2bpp)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonBigEndian)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonLittleEndian)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonFastDMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8bpp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4bpp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2bpp)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLittleEndian)
                    .addComponent(jRadioButtonBigEndian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        confirmed = true;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        confirmed = false;
        setVisible(false);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        confirmed = false;
    }//GEN-LAST:event_formWindowClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton2bpp;
    private javax.swing.JRadioButton jRadioButton4bpp;
    private javax.swing.JRadioButton jRadioButton8bpp;
    private javax.swing.JRadioButton jRadioButtonBigEndian;
    private javax.swing.JRadioButton jRadioButtonFastDMA;
    private javax.swing.JRadioButton jRadioButtonLittleEndian;
    private javax.swing.JRadioButton jRadioButtonTile;
    // End of variables declaration//GEN-END:variables
}
