/*
*  uChip Game Map Editor. A simple editor and integrated utility for tile-based games.
*
*  Copyright 2019-2020 Nicola Wrachien (next-hack.com)
*
*  This file is part of uChip Simple VGA Console Kernel Library.
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program  is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*  tl;dr
*  Do whatever you want, this program is free! Though we won't
*  reject donations https://next-hack.com/index.php/donate/ :)
*
*/

package uchipgamemapeditor;

import java.io.File;
import javax.swing.JFileChooser;

public class USVCPackagerDialog extends javax.swing.JDialog
{
    boolean confirmed = false;
    /**
     * Creates new form USVCPackagerDialog
     */
    public USVCPackagerDialog(java.awt.Frame parent, boolean modal, String binaryFileName, String metaFileName, String imageFileName, String outputFileName, String directory)
    {
        super(parent, modal);
        initComponents();
        if (binaryFileName != null && binaryFileName.length() > 0)
            jTextFieldBinaryFile.setText(binaryFileName);
        if (metaFileName != null && metaFileName.length() > 0)
            jTextFieldMetaFile.setText(metaFileName); 
        if (imageFileName != null && imageFileName.length() > 0)
            jTextFieldImageFile.setText(imageFileName);      
        if (outputFileName != null && outputFileName.length() > 0)
            jTextFieldOutputFile.setText(outputFileName);  
        if (directory != null && directory.length() > 0)
            jTextFieldDirectory.setText(directory);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldBinaryFile = new javax.swing.JTextField();
        jButtonChooseBinary = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMetaFile = new javax.swing.JTextField();
        jButtonChooseMeta = new javax.swing.JButton();
        jButtonChooseImage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldImageFile = new javax.swing.JTextField();
        jButtonChooseOutput = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOutputFile = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonChooseDirectory = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDirectory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create USVC Game File");

        jLabel1.setText("Binary File:");

        jTextFieldBinaryFile.setText("binary.bin");

        jButtonChooseBinary.setText("Choose");
        jButtonChooseBinary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseBinaryActionPerformed(evt);
            }
        });

        jLabel2.setText("Meta File:");

        jTextFieldMetaFile.setText("meta.txt");
        jTextFieldMetaFile.setToolTipText("Path to the file with the description");

        jButtonChooseMeta.setText("Choose");
        jButtonChooseMeta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseMetaActionPerformed(evt);
            }
        });

        jButtonChooseImage.setText("Choose");
        jButtonChooseImage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseImageActionPerformed(evt);
            }
        });

        jLabel3.setText("96x72 image:");

        jTextFieldImageFile.setText("image.png");
        jTextFieldImageFile.setToolTipText("Path to the file with the description");

        jButtonChooseOutput.setText("Choose");
        jButtonChooseOutput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseOutputActionPerformed(evt);
            }
        });

        jLabel4.setText("Output name:");

        jTextFieldOutputFile.setText("game.usc");
        jTextFieldOutputFile.setToolTipText("Path to the file with the description");

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose files separately...");

        jLabel6.setText("... or choose a directory where \"binary.bin\", \"meta.txt\", and \"image.png\" exist. \"game.usc\" will be created in the same directory. ");

        jButtonChooseDirectory.setText("Choose");
        jButtonChooseDirectory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseDirectoryActionPerformed(evt);
            }
        });

        jLabel7.setText("Directory");

        jTextFieldDirectory.setToolTipText("Path to the file with the description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOk)
                        .addGap(102, 102, 102)
                        .addComponent(jButtonCancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDirectory)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChooseDirectory))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldOutputFile)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChooseOutput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldImageFile)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChooseImage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBinaryFile, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChooseBinary))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMetaFile)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChooseMeta))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBinaryFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseBinary))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMetaFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseMeta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldImageFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseImage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseOutput))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOkActionPerformed
    {//GEN-HEADEREND:event_jButtonOkActionPerformed
        confirmed = true;
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonChooseBinaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseBinaryActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseBinaryActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File (jTextFieldBinaryFile.getText()));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            jTextFieldBinaryFile.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonChooseBinaryActionPerformed

    private void jButtonChooseMetaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseMetaActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseMetaActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File (jTextFieldMetaFile.getText()));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            jTextFieldMetaFile.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonChooseMetaActionPerformed

    private void jButtonChooseImageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseImageActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseImageActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File (jTextFieldImageFile.getText()));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            jTextFieldImageFile.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonChooseImageActionPerformed

    private void jButtonChooseOutputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseOutputActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseOutputActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File (jTextFieldOutputFile.getText()));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            jTextFieldOutputFile.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonChooseOutputActionPerformed

    private void jButtonChooseDirectoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseDirectoryActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseDirectoryActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File(jTextFieldDirectory.getText()));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            String dirName = fc.getSelectedFile().getAbsolutePath();
            if (!dirName.endsWith(File.separator))
                dirName += File.separator;
            jTextFieldDirectory.setText(dirName);
            jTextFieldBinaryFile.setText(dirName + "binary.bin");
            jTextFieldMetaFile.setText(dirName + "meta.txt");
            jTextFieldImageFile.setText(dirName + "image.png");
            jTextFieldOutputFile.setText(dirName + "game.usc");
        }
    }//GEN-LAST:event_jButtonChooseDirectoryActionPerformed
    String getDirectory()
    {
        return jTextFieldDirectory.getText();
    }
    String getOutputFileName()
    {
        return jTextFieldOutputFile.getText();
    }
    String getMetaFileName()
    {
        return jTextFieldMetaFile.getText();
    }
    String getImageFileName()
    {
        return jTextFieldImageFile.getText();
    }
    String getBinaryFileName()
    {
        return jTextFieldBinaryFile.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChooseBinary;
    private javax.swing.JButton jButtonChooseDirectory;
    private javax.swing.JButton jButtonChooseImage;
    private javax.swing.JButton jButtonChooseMeta;
    private javax.swing.JButton jButtonChooseOutput;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldBinaryFile;
    private javax.swing.JTextField jTextFieldDirectory;
    private javax.swing.JTextField jTextFieldImageFile;
    private javax.swing.JTextField jTextFieldMetaFile;
    private javax.swing.JTextField jTextFieldOutputFile;
    // End of variables declaration//GEN-END:variables
}
